site_name: EmbedIDS, Modern Intrusion Detection System (IDS) for Embedded Systems
site_author: Seyed Amir Alavi
site_url: https://embedids.samiralavi.io/
repo_name: samiralavi/embedids
docs_dir: "docs"
theme:
  name: material
  language: en
  icon:
    logo: material/contacts
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: teal
      accent: red

  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - toc:
      permalink: true
      toc_depth: 2

plugins:
  - search
  - mike

nav:
  - "index.md"

copyright: Copyright &copy; 2025 Seyed Amir Alavi.