name: Check Pull Request Title

on:
  pull_request:
    branches: [main, feat/*]

jobs:
  semantic_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check PR title uses conventional commit spec
        uses: amannn/action-semantic-pull-request@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat